version: '3'

services:
  mongodb:
    image: mongo:5.0.16
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 2s
      timeout: 5s
      retries: 120

  rabbitmq:
    image: rabbitmq:3.9.29-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 2s
      timeout: 5s
      retries: 120
