name: Code style

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.10", "3.11"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{matrix.version}}
        uses: actions/setup-python@v3.1.3
        with:
          python-version: ${{matrix.version}}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide
          
      - name: Lint with flake8
        run: |
          flake8 . --config=flake8.cfg --count --show-source
